### ISSUE TITLE
Current staging is not working in production setting

### ISSUE THREAD

**Issue by Baschdl** [match4healthcare/match4healthcare#216]
```
backend     | [2020-03-27 05:13:26 +0000] [16] [ERROR] Exception in worker process
backend     | Traceback (most recent call last):
backend     |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/arbiter.py", line 583, in spawn_worker
backend     |     worker.init_process()
backend     |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/ggevent.py", line 162, in init_process
backend     |     super().init_process()
backend     |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/base.py", line 119, in init_process
backend     |     self.load_wsgi()
backend     |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/base.py", line 144, in load_wsgi
backend     |     self.wsgi = self.app.wsgi()
backend     |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/base.py", line 67, in wsgi
backend     |     self.callable = self.load()
backend     |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/wsgiapp.py", line 49, in load
backend     |     return self.load_wsgiapp()
backend     |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
backend     |     return util.import_app(self.app_uri)
backend     |   File "/usr/local/lib/python3.6/dist-packages/gunicorn/util.py", line 358, in import_app
backend     |     mod = importlib.import_module(module)
backend     |   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
backend     |     return _bootstrap._gcd_import(name[level:], package, level)
backend     |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
backend     |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
backend     |   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
backend     |   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
backend     |   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
backend     |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
backend     |   File "/match4healthcare-backend/match4healthcare/wsgi.py", line 16, in <module>
backend     |     application = get_wsgi_application()
backend     |   File "/usr/local/lib/python3.6/dist-packages/django/core/wsgi.py", line 12, in get_wsgi_application
backend     |     django.setup(set_prefix=False)
backend     |   File "/usr/local/lib/python3.6/dist-packages/django/__init__.py", line 24, in setup
backend     |     apps.populate(settings.INSTALLED_APPS)
backend     |   File "/usr/local/lib/python3.6/dist-packages/django/apps/registry.py", line 114, in populate
backend     |     app_config.import_models()
backend     |   File "/usr/local/lib/python3.6/dist-packages/django/apps/config.py", line 211, in import_models
backend     |     self.models_module = import_module(models_module_name)
backend     |   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
backend     |     return _bootstrap._gcd_import(name[level:], package, level)
backend     |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
backend     |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
backend     |   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
backend     |   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
backend     |   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
backend     |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
backend     |   File "/match4healthcare-backend/apps/iamstudent/models.py", line 5, in <module>
backend     |     from apps.mapview.utils import plzs
backend     |   File "/match4healthcare-backend/apps/mapview/utils.py", line 20, in <module>
backend     |     df = pgeocode.Nominatim(countrycode)._data_frame.dropna()[["postal_code", "longitude", "latitude", "place_name"]].values
backend     |   File "/usr/local/lib/python3.6/dist-packages/pgeocode.py", line 71, in __init__
backend     |     self._data_path, self._data = self._get_data(country)
backend     |   File "/usr/local/lib/python3.6/dist-packages/pgeocode.py", line 86, in _get_data
backend     |     dtype={'postal_code': str})
backend     |   File "/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py", line 676, in parser_f
backend     |     return _read(filepath_or_buffer, kwds)
backend     |   File "/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py", line 448, in _read
backend     |     parser = TextFileReader(fp_or_buf, **kwds)
backend     |   File "/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py", line 880, in __init__
backend     |     self._make_engine(self.engine)
backend     |   File "/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py", line 1114, in _make_engine
backend     |     self._engine = CParserWrapper(self.f, **self.options)
backend     |   File "/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py", line 1891, in __init__
backend     |     self._reader = parsers.TextReader(src, **kwds)
backend     |   File "pandas/_libs/parsers.pyx", line 532, in pandas._libs.parsers.TextReader.__cinit__
backend     | pandas.errors.EmptyDataError: No columns to parse from file
backend     | [2020-03-27 05:13:26 +0000] [16] [INFO] Worker exiting (pid: 16)
backend     | [2020-03-27 05:13:30 +0000] [14] [INFO] Worker exiting (pid: 14)
backend     | Warning: count not make PLZ entry for OrderedDict([('plz', '8510'), ('lat', ' '), ('lon', ' '), ('ort', 'Wald in der Weststeiermark')])
backend     | [2020-03-27 05:13:30 +0000] [20] [INFO] Worker exiting (pid: 20)
backend     | Warning: count not make PLZ entry for OrderedDict([('plz', '8510'), ('lat', ' '), ('lon', ' '), ('ort', 'Wald in der Weststeiermark')])
backend     | [2020-03-27 05:13:31 +0000] [10] [INFO] Worker exiting (pid: 10)
backend     | Warning: count not make PLZ entry for OrderedDict([('plz', '8510'), ('lat', ' '), ('lon', ' '), ('ort', 'Wald in der Weststeiermark')])
backend     | [2020-03-27 05:13:31 +0000] [19] [INFO] Worker exiting (pid: 19)
backend     | Warning: count not make PLZ entry for OrderedDict([('plz', '8510'), ('lat', ' '), ('lon', ' '), ('ort', 'Wald in der Weststeiermark')])
backend     | [2020-03-27 05:13:31 +0000] [9] [INFO] Worker exiting (pid: 9)
backend     | Warning: count not make PLZ entry for OrderedDict([('plz', '8510'), ('lat', ' '), ('lon', ' '), ('ort', 'Wald in der Weststeiermark')])
backend     | [2020-03-27 05:13:31 +0000] [8] [INFO] Worker exiting (pid: 8)
backend     | Warning: count not make PLZ entry for OrderedDict([('plz', '8510'), ('lat', ' '), ('lon', ' '), ('ort', 'Wald in der Weststeiermark')])
backend     | [2020-03-27 05:13:31 +0000] [12] [INFO] Worker exiting (pid: 12)
backend     | Warning: count not make PLZ entry for OrderedDict([('plz', '8510'), ('lat', ' '), ('lon', ' '), ('ort', 'Wald in der Weststeiermark')])
backend     | [2020-03-27 05:13:32 +0000] [1] [INFO] Shutting down: Master
backend     | [2020-03-27 05:13:32 +0000] [1] [INFO] Reason: Worker failed to boot.
```

**Comment by feeds** [comment]
@Baschdl is this still an issue?

**Comment by Baschdl** [comment]
No, @josauder "fixed" it
